name: Build RPI4 OpenWrt Snapshot
on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 11 * * 0"
defaults:
  run:
    shell: bash
jobs:
  build-rpi4-openwrt-snapshot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Allow Script Execution
        run: |
          chmod +x .github/scripts/**/*.sh
      - name: Install Build System Dependencies
        run: .github/scripts/setup/install-buildsystem-dependencies.sh
      - name: Install Image Builder Dependencies
        run: .github/scripts/setup/install-imagebuilder-dependencies.sh
